### ISSUE TITLE
Support for OGF

### ISSUE THREAD

**Issue by wangi** [systemed/potlatch3#1]
Is it possible for Potlatch3 to have support for the [OpenGeofiction server](https://opengeofiction.net/), or other servers which implement the OSM API?

See also: https://opengeofiction.net/user/ADB52/diary/3079

**Comment by systemed** [comment]
P3 should now support this. (I haven't done a build yet, that'll be updated in due course.) It expects an OSM API and OSM-compatible OAuth handling. I've tested it with OpenGeofiction and it works fine.

You'll need to:

- open P3
- use the "Options" dialogue ("Connection" tab) to set these details:
   - Map data server: https://www.opengeofiction.net/api/0.6/
   - Overview tile server: https://tile.opengeofiction.net/osmcarto/
   - OAuth key: ujvIqRok6N6sdmZGcX4imnuTFebw0H6e7kYPZt9B
   - OAuth secret: 3IaRFnWT7EeSkbzlm719c7YuMHwVeuzEQDmkhDwn
- quit P3 and reopen it

Once you've done this the first time it should remember it from then on. When you're logging in to OpenGeoFiction within P3, you'll need to click "Try access" (bottom right) to continue at one point.

(The key/secret are just those I generated by logging into OGF and creating new ones - you can create them yourself if you like.)

**Comment by wangi** [comment]
Thank you
