### ISSUE TITLE
Close changeset before exit

### ISSUE THREAD

**Issue by SomeoneElseOSM** [systemed/potlatch3#15]
Another "nice to have", somewhat related to https://github.com/systemed/potlatch3/issues/9 .

I wouldn't want to close a changeset with every save, but closing before exiting (if possible) would be nice.  That way you don't end up with a changeset that stays open for an hour with "Changeset still open - discussion will open once the changeset is closed. " displayed at osm.org.

**Comment by systemed** [comment]
Fixed in https://github.com/systemed/potlatch3/commit/5a5fc99eeebb573be0f924a71fc97690f67014fa.
