### ISSUE TITLE
Save after "Logout" doesn't allow you to choose account

### ISSUE THREAD

**Issue by SomeoneElseOSM** [systemed/potlatch3#16]
I've "logged out" as "SomeoneElse_Revert" and I'd like to "login" as "SomeoneElse".  Unfortunately On save all I see is "Authorise access to your account" for "SomeoneElse_Revert" - there seems to be no obvious way to choose account here.

Is there a "login" option that I'm missing?

**Comment by systemed** [comment]
That appears to happen if you selected "Remember me" on the osm.org page when you first logged in. Potlatch just asks osm.org for the oauth page, it doesn't know who you are.

I would think if you nuke any cookies that AIR can see, that'd fix this. On Mac they appear to be shared with Safari; not sure about Windows. https://help.adobe.com/en_US/air/reference/html/flash/net/URLRequest.html#manageCookies

It might be a useful enhancement to openstreetmap-website for the "Authorize access to your account" page to have a "Log in as a different user" link to override the "remember me" setting.

**Comment by SomeoneElseOSM** [comment]
I may have had "remember me" ticked at some point in the past, but when I log in and out now in it isn't ticked.

**Comment by SomeoneElseOSM** [comment]
For completeness, the following have no effect:

* Clear all cookies in Firefox
* Clear all cookies in Chrome (and setting default browser to Chrome)
* Uninstall Potlatch and reinstall
* Uninstall Potlatch _and_ Adobe Air (uninstalling Potlatch on its own does not do this)
* Install Potlatch to a different location
* Changing to the dev API and back
* Rebooting

What did work, and in the light of your Safari comment perhaps ought to have been tried earlier:

* Clear all Cookies in Internet Explorer

**Comment by systemed** [comment]
> 10:58 (RichardF) so _probably_ clearing cookies from IE/Edge/whatever-it-is-this-week will also clear them from AIR, and therefore AIR won't tell osm.org it's logged in

Thought so :)

I've opened https://github.com/openstreetmap/openstreetmap-website/issues/3103.
