### ISSUE TITLE
NLS tile server location changed

### ISSUE THREAD

**Issue by tommycrock** [systemed/potlatch3#22]
Hello. My apologies, but as I've not used Potlatch I don't know if this is relevant but I trust it is / will be closed easily.

The National Library of Scotland have changed their preferred server locations for maps with national coverage. Chris Fleet, their map curator has updated the osm wiki page https://wiki.openstreetmap.org/wiki/National_Library_of_Scotland
I have updated the addresses in JOSM and they may need updating here.

Most old addresses still seem to work except the os 1:10,560, I'm not sure if this is a gradual swap over. I also noticed the 1:25k isn't listed on that page but a new address following the same pattern works.

Thanks

**Comment by systemed** [comment]
Thanks for the report. P3 uses https://github.com/osmlab/editor-layer-index so any changes made there will be picked up here.
