### ISSUE TITLE
The keyboard isn't working correctly

### ISSUE THREAD

**Issue by jrcarlsen** [systemed/potlatch3#26]
I'm using Potlatch 3.0 on a MacOS Monterey (12.1) on an M1 Pro Macbook.

Most keys on the keyboard works fine, but 'd' asks if you want begin dictation, and 'e' opens an emoticon selector.

Holding down CTRL allows all characters to be typed correctly.

Let me know what else I can provide to help troubleshooting this.

**Comment by systemed** [comment]
Very weird! Is that in text entry fields (eg tags) as well as hot keys?

**Comment by jrcarlsen** [comment]
It also applies to hotkeys.

It only affects the letters "d", "e" and "f". I've noticed that the menubar flashes when I hit those keys.

"d" and "e" makes the "Edit" menu flash, and both "Dictation" and "Emoji & Symbols" lives in there.
"f" makes  "Window" flash, but I haven't figure out what the effect is.

This is a new laptop, so I have never tried any prior versions of Potlatch on it.

**Comment by systemed** [comment]
This looks like https://github.com/airsdk/Adobe-Runtime-Support/issues/1323

I'll have a go at building with the new version of AIR and see if this resolves it.

**Comment by jrcarlsen** [comment]
Great, I'll be happy to test it when ready.

**Comment by NicolasDionB** [comment]
I've tested with the latest SDK 33.1.1.731 and the problem is still present. Any update on this?

**Comment by NicolasDionB** [comment]
It is fixed with the latest version, using the 33.1.1.713 SDK, it works fine. Cheers!

**Comment by systemed** [comment]
I've rebuilt P3 using the latest SDK - it's now on the downloads page. Let me know if it works for you.

**Comment by NicolasDionB** [comment]
I guess this can be closed then.

**Comment by jrcarlsen** [comment]
I can confirm, it works now.
