### ISSUE TITLE
creation of way without tag

### ISSUE THREAD

**Issue by Mahabarata** [systemed/potlatch3#31]
Hi,

I have created a multipolygon relation with 2 members : https://www.openstreetmap.org/relation/13958872/history
One member with no tag is the outer, the other with some tags is a inner.

* with Potlatch 3, I select the outer way
* on the left, I select "members"
* under, I select in the list "way 1043459092"
* above, in the relation table, I click on the cross to remove the way from the relation
* I save

No warning, no error : the save is sent.

Result : 
the way outer had no tags. It is no more member of the relation so we have an empty way (no tag) in the osm database
https://www.openstreetmap.org/edit?way=1043459092#map=18/4.89659/-52.34338
(this link is a link to ID editor)

Best regards

**Comment by systemed** [comment]
Thank you but this is not a bug. Potlatch 3 doesn't have a validator. If you would like it to have a validator you're welcome to build one, or - in case someone else wants to build it - to create a single ticket enumerating cases that it could trap.

**Comment by Mahabarata** [comment]
Hi,

I don't understand : try this with the example above =
* select one node of the inner way and delete it
* do the same for all the nodes of the inner way
* save

You will have a message = "Error :
An unexpected error occurred, probably due to a bug in Potlatch 2. Do you want to retry? (The server said: Precondition failed: Way 1043459093 is still used by relations 13958872.)"

If you have no validator, from where comes this message ?
Best regards

**Comment by systemed** [comment]
From the server.

**Comment by Mahabarata** [comment]
Yes, I had understood that : in fact I found that iD editor has the same problem. Rather than to fix it with your editor and some others, I was thinking to fix it "on the server" should be better. But I don't know what it means : where is the "server" ? Where can I create an issue to propose to solve this problme there ? Is it on github ? on a talk ?
Maybe you know ?
Best regards
