### ISSUE TITLE
Time taken to display "My Tracks"

### ISSUE THREAD

**Issue by SomeoneElseOSM** [systemed/potlatch3#34]
Currently the first time that "GPS/ My Tracks" is used in a session it takes 17 seconds to load.  I'm guessing that it might be loading everything historically (going back to 2008 for me)?  Would some sort of paged mode or user preference for start date (defaulting to the beginning of time) be an option?

I suspect I upload rather more GPS traces than most people, so this might be less of an issue elsewhere.

**Comment by systemed** [comment]
If you go to https://www.openstreetmap.org/api/0.6/user/gpx_files, does it take a similar amount of time?

**Comment by SomeoneElseOSM** [comment]
Very similar.  13 seconds at https://www.openstreetmap.org/api/0.6/user/gpx_files .

**Comment by systemed** [comment]
Ultimately then I guess this is an openstreetmap-website issue. As best I know, the `/api/0.6/user/gpx_files` call doesn't support pagination.

**Comment by SomeoneElseOSM** [comment]
Ah - fair enough (assuming that the display of GPS traces in P3 has to be synchronous)

**Comment by systemed** [comment]
In theory I guess we could keep the GPS trace list in local storage, show the cached list straightaway, and only refresh when the `gpx_files` call returns. But you're probably right that not many P3 users have 5000+ traces ;)

**Comment by mmd-osm** [comment]
> Ultimately then I guess this is an openstreetmap-website issue.

Right, that's why I've opened an issue there now.
