### ISSUE TITLE
Some imagery sources missing from Potlatch 3

### ISSUE THREAD

**Issue by SomeoneElseOSM** [systemed/potlatch3#35]
OS OpenData StreetView and OS OpenMap Local (e.g. https://c.os.openstreetmap.org/layer/gb_os_sv_2016_04/15/16342/10477.png and https://c.os.openstreetmap.org/layer/gb_os_om_local_2020_04/15/16342/10477.png ) are no longer available in Potlatch 3, as of this morning.

The underlying tiles still seem to be there, the the version of iD deployed on osm.org can still see them.

Inside the extracted zip file Potlatch_3_Windows_20220124/resources/imagery.xml is http://os.openstreetmap.org/sv/$z/$x/$y.png , and https://os.openstreetmap.org/layer/sv/15/16342/10477.png gives a 404.  I'm not sure if that's actually the file used though, as there's no "OS OpenData Local" in there.

**Comment by systemed** [comment]
Working fine for me this morning.

P3 pulls its imagery index from https://osmlab.github.io/editor-layer-index/imagery.json . I guess it's possible that  was down at the time you tried.

**Comment by SomeoneElseOSM** [comment]
Odd - still an issue for me.  Is there some way of refreshing the cache?

The json file that I can download via "wget https://osmlab.github.io/editor-layer-index/imagery.json" has both "OpenData StreetView" and "OpenMap Local" in it.

![Screen_2022050506_007](https://user-images.githubusercontent.com/5311740/167389654-4b3868b1-40be-486e-9edf-c32b4c2d648f.png)

Edit: I swapped the uploaded image to one zoomed in on the UK.

**Comment by systemed** [comment]
P3 doesn't cache this, it pulls it down every time you launch. If there's any caching going on I suspect it'll be at the OS level - I guess AIR could maybe maintain its own cache but that would seem weird given that this isn't a browser context, it's a fetch/ajax-type request.

**Comment by SomeoneElseOSM** [comment]
(re refreshing the cache) yes - just going into "edit" (which does show the full list) and then exiting does case it to reread the list that appears on the menu.
