### ISSUE TITLE
Changeset closed with no edit as far as I can tell

### ISSUE THREAD

**Issue by cliffordsnow** [systemed/potlatch3#41]
Changeset 136839530 from a new mapper, Doug Hayman, shows num_changes as 0. Is this possible?

**Comment by systemed** [comment]
Evidently so :)

I could believe there might be some weird edge case where you could confuse the "map is dirty" tracker with a combination of undo actions.

**Comment by cliffordsnow** [comment]
I did a search for similar changesets with num_changes = 0; Turns out there are quite a few involving all editors. I'm closing this with no action needed since this seems to be a common occurrence.
