### ISSUE TITLE
How come that imported GNSS tracks are shown distorted? 

### ISSUE THREAD

**Issue by tracker51** [systemed/potlatch3#46]
Hello,

When hiking, I always have a certain "companion": it's a multi-frequency GNSS receiver. Under good receiving conditions the recorded track can be **really** precise due to the application of SAPOS data which are free here in Lower Saxony (Germany). 

If I want to record the position of an object as precise as possible I just walk around it in a circle even risking that it may seem ridiculous to people passing by.

Before using one of these mentioned tracks for mapping I always check its precision by using the official maps of the Lower Saxony State Surveying Office which offers the possibility to overlay tracks on official maps and orthophotos in Geobasisdatenviewer (https://www.geobasis.niedersachsen.de/).

Following you can see a few of such marking circles on a screenshot made from a Geobasisdatenviewer orthophoto; you will find the  location here:  https://www.openstreetmap.org/#map=19/51.58203/10.62041

![Parkplatz_Walkenried_LGLN_englisch](https://github.com/systemed/potlatch3/assets/43145090/0036cfd1-3e66-4d24-bb0d-9af685732b3f)

Unfortunately, the track line is far to thick to identify the circled objects <shrugging>.

On the other hand, in Potlatch editor the same track line (here: blue) would be thin enough for identyfying the marked objects but it is distorted in a way that the circles are in no way displayed:

![Parkplatz_Walkenried_Potlatch](https://github.com/systemed/potlatch3/assets/43145090/ed76735f-ca9a-4dd4-b591-533da476ea92)

In the German OSM forum I was told that the track is displayed absolutely correct in JOSM and iD editors.

Therefore my question: Is it possible to enhance the display of imported GNSS tracks so that they are shown completely correct in Potlatch? I would very much welcome it, especially as it would also support the precice mapping of on-the-ground objects.

Best regards

tracker51

**Comment by systemed** [comment]
Can you upload the track somewhere so I can take a look?

**Comment by tracker51** [comment]
Hello,

You can find it as the newest uploaded track here: https://www.openstreetmap.org/user/tracker51/traces

Bye

tracker51

**Comment by systemed** [comment]
Thanks!

When loading from the GPS menu, Potlatch has a filter that won't write points within 3m of each other. This is to simplify the trace in the common case where you're just standing still for a while and the GPS signal moves slightly.

However, you can bypass this by loading the GPX directly into Potlatch, instead of through osm.org:

- Open "Background" menu
- Click "Vector file..."
- Click File: "Open..."
- Select the GPX file you want
- When the file loads, find the entry in the layer list above, and change the style to "GPS"

**Comment by tracker51** [comment]
Hello,

Many thanks. That did the trick :-)!

Best regards

reinhard
