### ISSUE TITLE
Potlatch 3.1, the application cannot be installed due to a certificate problem

### ISSUE THREAD

**Issue by jrcarlsen** [systemed/potlatch3#50]
Hi,

I am on a MacBook M1 with Sonoma 14.5.

I've installed AIR Runtime 51.0.1.3. When I try to run Potlatch 3 I get the following error:

![Screenshot 2567-07-04 at 19 07 04](https://github.com/systemed/potlatch3/assets/10294605/45b4c77d-cf10-486d-8f8b-325d2e6f129c)

**Comment by systemed** [comment]
AIR does this if you still have the old version of Potlatch installed, for some strange reason.

If you delete the old version, then try to install the latest version of Potlatch 3, it should be fine. (Or at least it is on my Mac.)

**Comment by jrcarlsen** [comment]
Confirmed, removing the old version allows the installation of the new version.
