### ISSUE TITLE
Won't run on my Mac (M2 mini, macOS 14.2.1)

### ISSUE THREAD

**Issue by mikemmm** [systemed/potlatch3#53]
<img width="592" alt="Screenshot 2024-10-14 at 8 40 35 AM" src="https://github.com/user-attachments/assets/eb7817a6-8d42-44a3-97e5-ffbcd762746f">

**Comment by systemed** [comment]
Do you have an old version still installed? For some reason AIR appears to object to that - I had the same error on my Mac (also an M2 mini) until I deleted the old one.

**Comment by mikemmm** [comment]
Yes, I did.  Deleting it took care of the issue.  Thanks!
