### ISSUE TITLE
Backgrounds SPW(allonie) do not load

### ISSUE THREAD

**Issue by gerdami** [systemed/potlatch3#8]
Of which the "SPW(allonie) most recent aerial imagery" that more up-to-date that default Bing.
Please note that it was already the case with P2.
But, this background (and the others SPW) is correctly displayed with **iD**.   

See for example https://www.openstreetmap.org/#map=19/50.57074/5.58471 where _SPW(allonie) most recent aerial imagery_ shows the bridge under construction.

**Comment by systemed** [comment]
Unfortunately this is a WMS imagery source and Potlatch doesn't support WMS (which is an even more antique technology than Flash ;) ). It shouldn't be showing in the menu so I'll fix that.
